//! Integration tests against transport streams produced by a real muxer.
//!
//! The synthetic muxer in `demux.rs` proves the demuxer against a stream we
//! control byte for byte. This file proves it against the messier output of
//! ffmpeg: real PSI repetition, real adaptation fields, real PES packing and
//! real bitrates.
//!
//! Fixtures are generated by `scripts/make-test-streams.sh` rather than
//! committed. When they are absent every test here skips, so the suite still
//! runs on a machine without ffmpeg.

use std::collections::BTreeMap;
use std::path::PathBuf;

use streamium_mpegts::{AccessUnit, Codec, Demuxer, Event, Program};

fn fixture(name: &str) -> Option<Vec<u8>> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    match std::fs::read(&path) {
        Ok(bytes) => Some(bytes),
        Err(_) => {
            eprintln!(
                "skipping: {} missing (run scripts/make-test-streams.sh)",
                path.display()
            );
            None
        }
    }
}

#[derive(Default)]
struct Demuxed {
    programs: Vec<Program>,
    units: BTreeMap<u16, Vec<AccessUnit>>,
    discontinuities: usize,
    sync_losses: usize,
    crc_errors: usize,
}

impl Demuxed {
    fn pids(&self) -> Vec<u16> {
        self.units.keys().copied().collect()
    }

    fn codec(&self, pid: u16) -> Option<Codec> {
        self.units
            .get(&pid)
            .and_then(|u| u.first())
            .map(|u| u.codec)
    }
}

/// Feed `bytes` to a demuxer in `chunk` sized pieces and collect everything.
fn demux(bytes: &[u8], chunk: usize) -> Demuxed {
    let mut d = Demuxer::new();
    let mut out = Demuxed::default();
    let collect = |events: Vec<Event>, out: &mut Demuxed| {
        for event in events {
            match event {
                Event::ProgramFound(p) => out.programs.push(p),
                Event::AccessUnit(au) => out.units.entry(au.pid).or_default().push(au),
                Event::Discontinuity { .. } => out.discontinuities += 1,
                Event::SyncLost { .. } => out.sync_losses += 1,
                Event::CrcError { .. } => out.crc_errors += 1,
                Event::Pcr { .. } => {}
            }
        }
    };
    for piece in bytes.chunks(chunk.max(1)) {
        d.push(piece);
        collect(d.events(), &mut out);
    }
    d.flush();
    collect(d.events(), &mut out);
    out
}

struct Expectation {
    file: &'static str,
    video_pid: u16,
    video_codec: Codec,
    audio_pid: u16,
    audio_codec: Codec,
    /// Every fixture is three seconds of 25 fps video.
    video_units: usize,
}

const EXPECTATIONS: &[Expectation] = &[
    Expectation {
        file: "h264_aac.ts",
        video_pid: 0x100,
        video_codec: Codec::H264,
        audio_pid: 0x101,
        audio_codec: Codec::AacAdts,
        video_units: 75,
    },
    Expectation {
        file: "hevc_ac3.ts",
        video_pid: 0x100,
        video_codec: Codec::H265,
        audio_pid: 0x101,
        audio_codec: Codec::Ac3,
        video_units: 75,
    },
    Expectation {
        file: "mpeg2_mp2.ts",
        video_pid: 0x100,
        video_codec: Codec::Mpeg2Video,
        audio_pid: 0x101,
        audio_codec: Codec::MpegAudio,
        video_units: 75,
    },
];

#[test]
fn demuxes_every_codec_combination_without_errors() {
    for e in EXPECTATIONS {
        let Some(bytes) = fixture(e.file) else {
            continue;
        };
        let out = demux(&bytes, 4096);

        assert_eq!(out.programs.len(), 1, "{}: one program expected", e.file);
        assert_eq!(
            out.sync_losses, 0,
            "{}: clean stream must never lose sync",
            e.file
        );
        assert_eq!(out.crc_errors, 0, "{}: PSI must pass CRC", e.file);
        assert_eq!(
            out.discontinuities, 0,
            "{}: clean stream has no gaps",
            e.file
        );
        assert_eq!(out.pids(), vec![e.video_pid, e.audio_pid], "{}", e.file);
        assert_eq!(out.codec(e.video_pid), Some(e.video_codec), "{}", e.file);
        assert_eq!(out.codec(e.audio_pid), Some(e.audio_codec), "{}", e.file);

        let video = &out.units[&e.video_pid];
        assert_eq!(
            video.len(),
            e.video_units,
            "{}: every frame must be delivered",
            e.file
        );
        assert!(
            video[0].random_access,
            "{}: playback must open on a key frame",
            e.file
        );
        assert!(
            video.iter().all(|u| u.pts.is_some()),
            "{}: every video access unit needs a presentation timestamp",
            e.file
        );
        assert!(
            video.iter().all(|u| !u.data.is_empty()),
            "{}: empty access units must never reach a decoder",
            e.file
        );

        // Decode order must never run backwards.
        let decode_order: Vec<u64> = video.iter().map(|u| u.dts.or(u.pts).unwrap()).collect();
        assert!(
            decode_order.windows(2).all(|w| w[0] <= w[1]),
            "{}: decode timestamps must not run backwards",
            e.file
        );

        // Presentation timestamps must be evenly spaced: 25 fps is 3600 ticks
        // of the 90 kHz clock.
        let mut presentation: Vec<u64> = video.iter().filter_map(|u| u.pts).collect();
        presentation.sort_unstable();
        presentation.dedup();
        assert_eq!(
            presentation.len(),
            video.len(),
            "{}: duplicate timestamps",
            e.file
        );
        for w in presentation.windows(2) {
            assert_eq!(w[1] - w[0], 3600, "{}: frames must be 40 ms apart", e.file);
        }

        // Roughly one key frame per second of content.
        let keyframes = video.iter().filter(|u| u.random_access).count();
        assert!(
            (2..=4).contains(&keyframes),
            "{}: {keyframes} key frames",
            e.file
        );

        let audio = &out.units[&e.audio_pid];
        assert!(!audio.is_empty(), "{}: audio expected", e.file);
        assert!(
            audio.iter().all(|u| u.pts.is_some()),
            "{}: audio needs timestamps",
            e.file
        );
    }
}

#[test]
fn chunk_size_does_not_change_the_output() {
    let Some(bytes) = fixture("h264_aac.ts") else {
        return;
    };
    let reference = demux(&bytes, 65536);
    // One byte at a time is the pathological case: every packet, PES header
    // and PSI section is split across calls.
    for chunk in [1, 7, 188, 189, 1316, 1500, 4096] {
        let out = demux(&bytes, chunk);
        assert_eq!(
            out.programs, reference.programs,
            "chunk {chunk}: program mismatch"
        );
        assert_eq!(
            out.units, reference.units,
            "chunk {chunk}: access unit mismatch"
        );
        assert_eq!(out.sync_losses, 0, "chunk {chunk}: spurious resync");
        assert_eq!(
            out.discontinuities, 0,
            "chunk {chunk}: spurious discontinuity"
        );
    }
}

#[test]
fn joining_a_stream_in_progress_starts_at_a_key_frame() {
    let Some(bytes) = fixture("h264_aac.ts") else {
        return;
    };
    // Tuning into a live stream lands at an arbitrary byte, usually neither
    // packet aligned nor at a key frame.
    for offset in [1, 4097, 100_001, 250_003, 400_007] {
        assert!(offset < bytes.len());
        let out = demux(&bytes[offset..], 1500);
        let Some(video) = out.units.get(&0x100) else {
            continue;
        };
        if video.is_empty() {
            continue;
        }
        assert!(
            video[0].random_access,
            "offset {offset}: the first frame handed to the decoder must be a key frame"
        );
        assert!(
            out.crc_errors == 0,
            "offset {offset}: corrupt PSI must not be acted on"
        );
        let decode_order: Vec<u64> = video.iter().map(|u| u.dts.or(u.pts).unwrap()).collect();
        assert!(
            decode_order.windows(2).all(|w| w[0] <= w[1]),
            "offset {offset}: decode timestamps must not run backwards"
        );
    }
}

#[test]
fn packet_loss_is_reported_and_playback_re_gates_on_a_key_frame() {
    let Some(bytes) = fixture("h264_aac.ts") else {
        return;
    };
    // Drop a run of bytes from the middle, as a congested network would.
    let mut lossy = Vec::with_capacity(bytes.len());
    lossy.extend_from_slice(&bytes[..200_000]);
    lossy.extend_from_slice(&bytes[203_000..]);

    let out = demux(&lossy, 8192);
    assert!(
        out.discontinuities > 0,
        "the gap must be reported to the player"
    );

    let video = &out.units[&0x100];
    assert!(!video.is_empty());
    assert!(
        video[0].random_access,
        "playback must still open on a key frame"
    );

    // After the gap the demuxer must withhold frames until the next random
    // access point: frames that reference lost data would decode to artefacts.
    let clean = demux(&bytes, 8192);
    let clean_video = clean.units[&0x100].len();
    assert!(
        video.len() < clean_video,
        "frames referencing lost data must be withheld ({} of {clean_video} delivered)",
        video.len()
    );

    // Every delivered frame must belong to a run that started at a key frame.
    let mut have_key = false;
    for unit in video {
        if unit.random_access {
            have_key = true;
        }
        assert!(
            have_key,
            "a frame was delivered before any key frame in its run"
        );
    }
}

#[test]
fn garbage_before_the_stream_is_skipped() {
    let Some(bytes) = fixture("h264_aac.ts") else {
        return;
    };
    let mut noisy = Vec::new();
    // A stray sync byte pattern that is not a real packet, then random bytes.
    noisy.extend(std::iter::repeat_n([0x47u8, 0x11, 0x22, 0xFF], 50).flatten());
    noisy.extend((0..777u32).map(|i| i.wrapping_mul(2_654_435_761) as u8));
    noisy.extend_from_slice(&bytes);

    let out = demux(&noisy, 65536);
    assert!(out.sync_losses > 0, "the garbage must be reported");
    let clean = demux(&bytes, 65536);
    assert_eq!(
        out.units[&0x100].len(),
        clean.units[&0x100].len(),
        "after resync the stream must play in full"
    );
}

#[test]
fn every_program_in_a_multi_service_mux_is_discovered() {
    let Some(bytes) = fixture("multiprogram.ts") else {
        return;
    };
    let out = demux(&bytes, 4096);
    assert_eq!(out.programs.len(), 2, "both services must be found");

    let numbers: Vec<u16> = out.programs.iter().map(|p| p.number).collect();
    assert_eq!(numbers, vec![1, 2]);
    for program in &out.programs {
        assert_eq!(
            program.streams.len(),
            2,
            "program {} streams",
            program.number
        );
        assert!(program.streams.iter().any(|s| s.codec.is_video()));
        assert!(program.streams.iter().any(|s| s.codec.is_audio()));
        for stream in &program.streams {
            assert!(
                out.units.contains_key(&stream.pid),
                "program {} pid 0x{:04x} produced no access units",
                program.number,
                stream.pid
            );
        }
    }
    assert_eq!(out.crc_errors, 0);
    assert_eq!(out.sync_losses, 0);
}

#[test]
fn truncating_mid_packet_never_panics_and_loses_at_most_one_unit() {
    let Some(bytes) = fixture("h264_aac.ts") else {
        return;
    };
    let full = demux(&bytes, 4096).units[&0x100].len();
    // Cut the stream at an arbitrary point, as a dropped connection would.
    for cut in [bytes.len() - 1, bytes.len() - 94, bytes.len() - 500] {
        let out = demux(&bytes[..cut], 4096);
        let delivered = out.units.get(&0x100).map(Vec::len).unwrap_or(0);
        assert!(delivered <= full);
        assert!(
            delivered + 2 >= full,
            "a truncated tail must not lose the whole stream"
        );
    }
}
